SET
	SEARCH_PATH TO SOCIALNET7;

WITH RECURSIVE
	ACTIVE_PERIOD_PARAMS AS (
		SELECT
			INTERVAL '14 day' AS ALLOWED_GAP,
			'2020-05-10'::DATE AS OBSERVE_END,
			'2020-02-09'::DATE AS OBSERVE_START
	),
	END_DATES AS (
		--this are all the end_dates 
		SELECT DISTINCT
			ACCOUNT_ID,
			START_DATE,
			END_DATE,
			(END_DATE + ALLOWED_GAP)::DATE AS EXTENSION_MAX
		FROM
			SUBSCRIPTION
			INNER JOIN ACTIVE_PERIOD_PARAMS ON END_DATE BETWEEN OBSERVE_START AND OBSERVE_END
	),
	EXTENSIONS AS (
		--todas estas son os end_dates que tienen extension
		SELECT DISTINCT
			E.ACCOUNT_ID,
			E.END_DATE
		FROM
			END_DATES E
			INNER JOIN SUBSCRIPTION S ON E.ACCOUNT_ID = S.ACCOUNT_ID
			AND S.START_DATE <= E.EXTENSION_MAX
			AND (
				S.END_DATE > E.END_DATE
				OR S.END_DATE IS NULL
			)
	),
	CHURNS AS (
		--churned
		SELECT
			E.ACCOUNT_ID,
			E.START_DATE,
			E.END_DATE AS CHURN_DATE
		FROM
			END_DATES E
			LEFT OUTER JOIN EXTENSIONS X ON E.ACCOUNT_ID = X.ACCOUNT_ID
			AND E.END_DATE = X.END_DATE
		WHERE
			X.ACCOUNT_ID IS NULL
		UNION
		SELECT
			S.ACCOUNT_ID,
			S.START_DATE,
			E.CHURN_DATE
		FROM
			SUBSCRIPTION S
			CROSS JOIN ACTIVE_PERIOD_PARAMS
			INNER JOIN CHURNS E ON S.ACCOUNT_ID = E.ACCOUNT_ID
			AND S.START_DATE < E.START_DATE
			AND S.END_DATE >= (E.START_DATE - ALLOWED_GAP)::DATE
	)
	--los churn dates con sus periodos
INSERT INTO
	ACTIVE_PERIOD (ACCOUNT_ID, START_DATE, CHURN_DATE)
SELECT
	ACCOUNT_ID,
	MIN(START_DATE) AS START_DATE,
	CHURN_DATE
FROM
	CHURNS
GROUP BY
	ACCOUNT_ID,
	CHURN_DATE
ORDER BY
	ACCOUNT_ID