SET
	SEARCH_PATH TO SOCIALNET7,
	PUBLIC;

SHOW SEARCH_PATH;

--time series statistics
WITH
	DATE_RANGE AS (
		SELECT
			I::TIMESTAMP AS CALC_DATE
		FROM
			GENERATE_SERIES('2020-02-09', '2020-03-15', '7 day'::INTERVAL) I
	),
	THE_METRIC AS (
		SELECT
			*
		FROM
			METRIC AS M
			INNER JOIN METRIC_NAME AS N ON M.METRIC_NAME_ID = N.METRIC_NAME_ID
		WHERE
			N.METRIC_NAME = 'like_per_month'
	)
SELECT
	CALC_DATE,
	AVG(METRIC_VALUE),
	COUNT(THE_METRIC.*) AS N_CALC,
	MIN(METRIC_VALUE),
	MAX(METRIC_VALUE)
FROM
	DATE_RANGE
	LEFT OUTER JOIN THE_METRIC ON CALC_DATE = METRIC_TIME
GROUP BY
	CALC_DATE