SET
	SEARCH_PATH TO SOCIALNET7;

WITH
	DATE_RANGE AS (
		SELECT
			'2020-02-01'::TIMESTAMP AS START_DATE,
			'2020-05-31'::TIMESTAMP AS END_DATE
	),
	ACCOUNT_COUNT AS (
		--las cuentas activas en este periodo distintas
		SELECT
			COUNT(DISTINCT ACCOUNT_ID) AS N_ACCOUNT
		FROM
			--a esta cosa le vale madre con que este dentro 
			SUBSCRIPTION S
			INNER JOIN DATE_RANGE D ON S.START_DATE <= D.END_DATE
			AND (
				S.END_DATE >= D.START_DATE
				OR S.END_DATE IS NULL
			)
	)
SELECT
	EVENT_TYPE_NAME,
	N_ACCOUNT AS N_ACCOUNT,
	COUNT(*) AS N_EVENT,
	--numero de eventos en ese periodo
	--numero de cuentas activas en ese periodo
	--numero de eventos por cuenta
	COUNT(*)::FLOAT / N_ACCOUNT::FLOAT AS EVENTS_PER_ACCOUNT,
	EXTRACT(
		DAYS
		FROM
			END_DATE - START_DATE
	)::FLOAT / 28 AS N_MONTHS,
	--numero de eventos por cuenta por año por mes 
	(COUNT(*)::FLOAT / N_ACCOUNT::FLOAT) / (
		EXTRACT(
			DAYS
			FROM
				END_DATE - START_DATE
		)::FLOAT / 28
	) AS EVENTS_PER_ACCOUNT_PER_MONTH
FROM
	EVENT E
	CROSS JOIN ACCOUNT_COUNT
	INNER JOIN EVENT_TYPE T ON E.EVENT_TYPE_ID = T.EVENT_TYPE_ID
	INNER JOIN DATE_RANGE ON EVENT_TIME >= START_DATE
	AND EVENT_TIME <= END_DATE
GROUP BY
	EVENT_TYPE_NAME,
	N_ACCOUNT,
	END_DATE,
	START_DATE
ORDER BY
	EVENTS_PER_ACCOUNT_PER_MONTH DESC