SET
	SEARCH_PATH TO SOCIALNET7;

WITH
	DATE_RANGE AS (
		SELECT
			I::TIMESTAMP AS CALC_DATE
		FROM
			GENERATE_SERIES('2020-01-01', '2020-12-31', '1 day'::INTERVAL) I
	)
SELECT
	EVENT_TIME::DATE AS EVENT_DATE,
	COUNT(*) AS N_EVENT
FROM
	DATE_RANGE D
	LEFT OUTER JOIN EVENT E ON CALC_DATE = EVENT_TIME::DATE
	INNER JOIN EVENT_TYPE T ON E.EVENT_TYPE_ID = T.EVENT_TYPE_ID
WHERE
	T.EVENT_TYPE_NAME = 'like'
GROUP BY
	EVENT_DATE
ORDER BY
	EVENT_DATE