SET
	SEARCH_PATH TO SOCIALNET7,
	PUBLIC;

SHOW SEARCH_PATH;

WITH
	DATE_RANGE AS (
		SELECT
			'2020-03-01'::DATE AS START_DATE,
			'2020-04-01'::DATE AS END_DATE
	),
	START_ACCOUNTS AS (
		SELECT
			ACCOUNT_ID,
			SUM(MRR) AS TOTAL_MRR
		FROM
			SUBSCRIPTION
			INNER JOIN DATE_RANGE ON SUBSCRIPTION.START_DATE <= DATE_RANGE.START_DATE
			AND (
				SUBSCRIPTION.END_DATE > DATE_RANGE.START_DATE
				OR SUBSCRIPTION.END_DATE IS NULL
			)
		GROUP BY
			ACCOUNT_ID
		ORDER BY
			TOTAL_MRR DESC
	),
	END_ACCOUNTS AS (
		SELECT
			ACCOUNT_ID,
			SUM(MRR) AS TOTAL_MRR
		FROM
			SUBSCRIPTION
			INNER JOIN DATE_RANGE ON SUBSCRIPTION.START_DATE <= DATE_RANGE.END_DATE
			AND (
				SUBSCRIPTION.END_DATE > DATE_RANGE.END_DATE
				OR SUBSCRIPTION.END_DATE IS NULL
			)
		GROUP BY
			ACCOUNT_ID
		ORDER BY
			TOTAL_MRR DESC
	),
	CHURNED_ACCOUNTS AS (
		SELECT
			S.ACCOUNT_ID,
			SUM(S.TOTAL_MRR) AS TOTAL_MRR
		FROM
			START_ACCOUNTS AS S
			LEFT OUTER JOIN END_ACCOUNTS AS E ON S.ACCOUNT_ID = E.ACCOUNT_ID
		WHERE
			E.ACCOUNT_ID IS NULL
		GROUP BY
			S.ACCOUNT_ID
	),
	--entre las retenidas porque no fueron churns
	--cuantas bajaron 
	DOWNSELL_ACCOUNTS AS (
		SELECT
			S.ACCOUNT_ID,
			S.TOTAL_MRR - E.TOTAL_MRR AS DOWNSELL_AMOUNT
		FROM
			START_ACCOUNTS AS S
			INNER JOIN END_ACCOUNTS AS E ON S.ACCOUNT_ID = E.ACCOUNT_ID
		WHERE
			E.TOTAL_MRR < S.TOTAL_MRR
	),
	START_MRR AS (
		SELECT
			SUM(TOTAL_MRR) AS START_MRR
		FROM
			START_ACCOUNTS
	),
	CHURN_MRR AS (
		SELECT
			SUM(TOTAL_MRR) AS CHURN_MRR
		FROM
			CHURNED_ACCOUNTS
	)
SELECT
	*
FROM
	CHURN_MRR