--aqui nomas dice que ahi tiene 10 10
SET
	SEARCH_PATH TO SOCIALNET7,
	PUBLIC;

SHOW SEARCH_PATH;

WITH
	DATE_RANGE AS (
		SELECT
			'2020-03-01'::DATE AS START_DATE,
			'2020-04-01'::DATE AS END_DATE
	),
	--en ese dia
	START_ACCOUNTS AS (
		SELECT
			ACCOUNT_ID,
			SUM(MRR) AS TOTAL_MRR
		FROM
			SUBSCRIPTION
			INNER JOIN DATE_RANGE ON SUBSCRIPTION.START_DATE <= DATE_RANGE.START_DATE
			AND (
				SUBSCRIPTION.END_DATE > DATE_RANGE.START_DATE
				OR SUBSCRIPTION.END_DATE IS NULL
			)
		GROUP BY
			ACCOUNT_ID
		ORDER BY
			TOTAL_MRR DESC
	),
	END_ACCOUNTS AS (
		SELECT
			ACCOUNT_ID,
			SUM(MRR) AS TOTAL_MRR
		FROM
			SUBSCRIPTION
			INNER JOIN DATE_RANGE ON SUBSCRIPTION.START_DATE <= DATE_RANGE.END_DATE
			AND (
				SUBSCRIPTION.END_DATE > DATE_RANGE.END_DATE
				OR SUBSCRIPTION.END_DATE IS NULL
			)
		GROUP BY
			ACCOUNT_ID
		ORDER BY
			TOTAL_MRR DESC
	),
	--es una consecucion 
	RETAINED_ACCOUNTS AS (
		SELECT
			S.ACCOUNT_ID,
			SUM(E.TOTAL_MRR) AS TOTAL_MRR
		FROM
			START_ACCOUNTS AS S
			INNER JOIN END_ACCOUNTS AS E ON S.ACCOUNT_ID = E.ACCOUNT_ID
		GROUP BY
			S.ACCOUNT_ID
		ORDER BY
			TOTAL_MRR
	),
	START_MRR AS (
		SELECT
			SUM(S.TOTAL_MRR) AS START_MRR
		FROM
			START_ACCOUNTS AS S
	),
	RETAIN_MRR AS (
		SELECT
			SUM(R.TOTAL_MRR) AS RETAIN_MRR
		FROM
			RETAINED_ACCOUNTS AS R
	)
SELECT
	RETAIN_MRR / START_MRR AS NET_RETENTION_RATE,
	1.0 - RETAIN_MRR / START_MRR AS NET_CHURN_RATE,
	START_MRR,
	RETAIN_MRR
FROM
	START_MRR,
	RETAIN_MRR