SET
	SEARCH_PATH TO SOCIALNET7;

WITH RECURSIVE
	PARAMS AS (
		SELECT
			INTERVAL '1 month' AS OBS_INTERVAL,
			INTERVAL '1 week' AS LEAD_TIME,
			'2020-02-09'::DATE AS OBS_START,
			'2020-05-10'::DATE AS OBS_END
	),
	OBS AS (
		SELECT
			ACCOUNT_ID,
			START_DATE,
			1 AS OBS_COUNT,
			(START_DATE + OBS_INTERVAL - LEAD_TIME)::DATE AS OBS_DATE,
			CASE
				WHEN CHURN_DATE >= (START_DATE + OBS_INTERVAL - LEAD_TIME)::DATE
				AND CHURN_DATE < (START_DATE + 2 * OBS_INTERVAL - LEAD_TIME)::DATE THEN TRUE
				ELSE FALSE
			END AS IS_CHURN
			--CHURN_DATE AS CHURN_DATE
		FROM
			ACTIVE_PERIOD A
			INNER JOIN PARAMS ON CHURN_DATE > (OBS_START + OBS_INTERVAL - LEAD_TIME)::DATE
			OR CHURN_DATE IS NULL
		UNION
		SELECT
			O.ACCOUNT_ID,
			O.START_DATE,
			O.OBS_COUNT + 1,
			(
				O.START_DATE + (O.OBS_COUNT + 1) * OBS_INTERVAL - LEAD_TIME
			)::DATE,
			CASE
				WHEN CHURN_DATE >= (
					O.START_DATE + (O.OBS_COUNT + 1) * OBS_INTERVAL - LEAD_TIME
				)::DATE
				AND CHURN_DATE < (
					O.START_DATE + (O.OBS_COUNT + 2) * OBS_INTERVAL - LEAD_TIME
				)::DATE THEN TRUE
				ELSE FALSE
			END AS IS_CHURN
		FROM
			--le falta a esta tabla
			OBS O
			INNER JOIN PARAMS ON (
				O.START_DATE + (O.OBS_COUNT + 1) * OBS_INTERVAL - LEAD_TIME
			)::DATE <= OBS_END
	)
SELECT
	*
FROM
	OBS