SET
	SEARCH_PATH TO SOCIALNET7,
	PUBLIC;

SHOW SEARCH_PATH;

--para todas las fechas que sean menor a esa te las pone 
WITH
	DATE_VALS AS (
		--siempre hay 7 de diferencia
		SELECT
			I::TIMESTAMP AS METRIC_DATE
		FROM
			GENERATE_SERIES('2020-01-29', '2020-04-16', '7 day'::INTERVAL) AS I
	)
INSERT INTO
	METRIC (
		ACCOUNT_ID,
		METRIC_TIME,
		METRIC_NAME_ID,
		METRIC_VALUE
	)
SELECT
	ACCOUNT_ID,
	METRIC_DATE,
	0,
	COUNT(*) AS METRIC_VALUE
FROM
	EVENT AS E
	INNER JOIN DATE_VALS AS D ON E.EVENT_TIME < D.METRIC_DATE
	AND E.EVENT_TIME >= D.METRIC_DATE - INTERVAL '28 day'
	INNER JOIN EVENT_TYPE AS T ON E.EVENT_TYPE_ID = T.EVENT_TYPE_ID
WHERE
	T.EVENT_TYPE_NAME = 'post'
GROUP BY
	ACCOUNT_ID,
	METRIC_DATE
ORDER BY
	ACCOUNT_ID,
	METRIC_DATE