SET
	SEARCH_PATH TO SOCIALNET7,
	PUBLIC;

SHOW SEARCH_PATH;

WITH
	DATE_RANGE AS (
		SELECT
			'2020-03-01'::DATE AS START_DATE,
			'2020-04-01'::DATE AS END_DATE
	),
	--cuentas activas en ese periodo no te importa si tiene multiples 
	START_ACCOUNTS AS (
		SELECT DISTINCT
			ACCOUNT_ID
		FROM
			SUBSCRIPTION AS S
			INNER JOIN DATE_RANGE AS D ON S.START_DATE <= D.START_DATE
			AND (
				S.END_DATE > D.START_DATE
				OR S.END_DATE IS NULL
			)
	),
	--cuentas activas en el periodo del end date 
	END_ACCOUNTS AS (
		SELECT DISTINCT
			ACCOUNT_ID
		FROM
			SUBSCRIPTION AS S
			INNER JOIN DATE_RANGE AS D ON S.START_DATE <= D.END_DATE
			AND (
				S.END_DATE > D.END_DATE
				OR S.END_DATE IS NULL
			)
	),
	CHURNED_ACCOUNTS AS (
		SELECT
			*
		FROM
			START_ACCOUNTS AS S
			LEFT OUTER JOIN END_ACCOUNTS AS E ON S.ACCOUNT_ID = E.ACCOUNT_ID
		WHERE
			E.ACCOUNT_ID IS NULL
	),
	START_COUNT AS (
		SELECT
			COUNT(*) AS N_START
		FROM
			START_ACCOUNTS
	),
	CHURN_COUNT AS (
		SELECT
			COUNT(*) AS N_CHURN
		FROM
			CHURNED_ACCOUNTS
	)
SELECT
	N_CHURN::FLOAT / N_START::FLOAT * 100 AS CHURN_RATE,
	(1.0 - N_CHURN::FLOAT / N_START::FLOAT) * 100 AS RETENTION_RATE,
	N_START,
	N_CHURN
FROM
	CHURN_COUNT,
	START_COUNT