SET
	SEARCH_PATH TO SOCIALNET7;

WITH RECURSIVE
	DATE_VALS AS (
		SELECT
			I::TIMESTAMP AS METRIC_DATE
		FROM
			GENERATE_SERIES('2020-02-02', '2020-05-10', '7 day'::INTERVAL) I
	),
	ALL_DAYS AS (
		SELECT
			ACCOUNT_ID,
			METRIC_DATE,
			MIN(START_DATE) AS START_DATE
		FROM
			SUBSCRIPTION S
			INNER JOIN DATE_VALS D ON START_DATE <= METRIC_DATE
			AND (
				END_DATE > METRIC_DATE
				OR END_DATE IS NULL
			)
		GROUP BY
			ACCOUNT_ID,
			METRIC_DATE
		UNION ALL
		SELECT
			S.ACCOUNT_ID,
			METRIC_DATE,
			S.START_DATE
		FROM
			SUBSCRIPTION S
			INNER JOIN ALL_DAYS A ON S.ACCOUNT_ID = A.ACCOUNT_ID
			AND S.START_DATE < A.START_DATE
			AND S.END_DATE >= (A.START_DATE - 31) --gap
	),
	MAIN_CALC AS (
		--tiene repetidos las cuentas porq?
		SELECT
			ACCOUNT_ID,
			MIN(START_DATE) AS EARLIEST_START,
			D.METRIC_DATE - MIN(START_DATE) AS ACCOUNT_TENURE
		FROM
			ALL_DAYS
			CROSS JOIN DATE_VALS D
		GROUP BY
			ACCOUNT_ID,
			D.METRIC_DATE
		ORDER BY
			ACCOUNT_ID
	),
	ALE AS (
		SELECT
			ACCOUNT_ID,
			METRIC_DATE,
			--MIN(START_DATE),
			8 AS METRIC_NAME_ID,
			EXTRACT(
				DAYS
				FROM
					METRIC_DATE - MIN(START_DATE)
			) AS METRIC_VALUE
		FROM
			ALL_DAYS
		GROUP BY
			ACCOUNT_ID,
			METRIC_DATE
		ORDER BY
			ACCOUNT_ID,
			METRIC_DATE
	)
	/*
INSERT INTO
	METRIC (
		ACCOUNT_ID,
		METRIC_TIME,
		METRIC_NAME_ID,
		METRIC_VALUE
	)*/
SELECT
	*
FROM
	ALE