SET
	SEARCH_PATH TO SOCIALNET7;

WITH RECURSIVE
	ACTIVE_PERIOD_PARAMS AS (
		SELECT
			INTERVAL '7 days' AS ALLOWED_GAP,
			'2020-05-10'::DATE AS CALC_DATE
	),
	ACTIVE AS (
		--estas son las cuentas activas en este periodo
		SELECT
			ACCOUNT_ID,
			MIN(START_DATE) AS START_DATE
		FROM
			SUBSCRIPTION
			INNER JOIN ACTIVE_PERIOD_PARAMS ON START_DATE <= CALC_DATE
			AND (
				END_DATE > CALC_DATE
				OR END_DATE IS NULL
			)
		GROUP BY
			ACCOUNT_ID
		UNION
		SELECT
			S.ACCOUNT_ID,
			S.START_DATE
		FROM
			SUBSCRIPTION S
			--esta es para que puedas usar la data 
			CROSS JOIN ACTIVE_PERIOD_PARAMS
			INNER JOIN ACTIVE E ON S.ACCOUNT_ID = E.ACCOUNT_ID
			AND S.START_DATE < E.START_DATE
			AND S.END_DATE >= (E.START_DATE - ALLOWED_GAP)::DATE
	)
INSERT INTO
	ACTIVE_PERIOD (ACCOUNT_ID, START_DATE, CHURN_DATE)
SELECT
	ACCOUNT_ID,
	MIN(START_DATE) AS START_DATE,
	NULL::DATE AS CHURN_DATE
FROM
	ACTIVE
GROUP BY
	ACCOUNT_ID