SET
	SEARCH_PATH TO SOCIALNET7,
	PUBLIC;

SHOW SEARCH_PATH;

WITH
	CALC_DATE AS (
		SELECT
			'2020-05-06'::TIMESTAMP AS THE_DATE
	)
	--todos los likes del mes pasado 
SELECT
	ACCOUNT_ID,
	COUNT(*) AS N_LIKE_PERMONTH
FROM
	EVENT AS E
	INNER JOIN CALC_DATE AS C ON E.EVENT_TIME <= C.THE_DATE
	AND E.EVENT_TIME > (C.THE_DATE - INTERVAL '28 day')
	INNER JOIN EVENT_TYPE AS T ON E.EVENT_TYPE_ID = T.EVENT_TYPE_ID
WHERE
	T.EVENT_TYPE_NAME = 'like'
GROUP BY
	ACCOUNT_ID
ORDER BY
	N_LIKE_PERMONTH DESC